/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queryB;
import p.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wayne
 */
public class consulta2_2 extends javax.swing.JFrame {

    /**
     * Creates new form consulta2_2
     */
    public consulta2_2() throws IOException {
        initComponents();
        TextFile prueba = new TextFile();
        prueba.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Employees.txt");
        String line =  prueba.readLine();
        String[] columnas = line.split(",");
        ArrayList<cabeza> cabezas = new ArrayList<>();
        
        for (int i = 1; i < columnas.length-2; i+=3) {
            cabezas.add(new cabeza(columnas[i], Integer.parseInt(columnas[i+1]),Integer.parseInt(columnas[i+2])));
        }
        
        TextFile prueba2 = new TextFile();
        prueba2.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Departmets.txt");
        String line2 =  prueba2.readLine();
        String[] columnas2 = line2.split(",");
        ArrayList<cabeza> cabezas2 = new ArrayList<>();
        
        
        for (int i = 1; i < columnas2.length-2; i+=3) {
            cabezas2.add(new cabeza(columnas2[i], Integer.parseInt(columnas2[i+1]), Integer.parseInt(columnas2[i+2])));
        }
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" ");//n0
        
        for (int i = 0; i < cabezas.size(); i++) {
            System.out.println(cabezas.get(i).getNombre());
            model.addColumn(cabezas.get(i).getNombre());
        }
        for (int i = 0; i < cabezas2.size(); i++) {
            System.out.println(cabezas2.get(i).getNombre());
            model.addColumn(cabezas2.get(i).getNombre());
        }
        
        int cont=1;
        
        while ((line = prueba.readLine()) != null) {
            Object a[] = new Object[cabezas.size()+1+cabezas2.size()];
            
          
            a[0]=cont;
            int aux=0;
            for (int i = 0; i < cabezas.size(); i++) {
                a[i+1]=line.substring(cabezas.get(i).getA(), cabezas.get(i).getB());
                aux=i+1;
            }
            prueba2.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Departmets.txt");
            line2 =  prueba2.readLine();
            line2 =  prueba2.readLine();
            while ((line2=prueba2.readLine())!=null) {                
                a[0]=cont;
                for (int j = 0; j <cabezas2.size(); j++) {
                    a[j+1+aux]=line2.substring(cabezas2.get(j).getA(), cabezas2.get(j).getB());
                    
                }
                
                model.addRow(a);
                cont++;
            }
            
        }
        jTable1.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            consulta2_3 ventana;
            ventana = new consulta2_3();
            ventana.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(consulta2_2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
