/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queryB;
import p.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wayne
 */
public class consulta2_3 extends javax.swing.JFrame {

    /**
     * Creates new form consulta2_3
     */
    public consulta2_3() throws IOException {
        initComponents();
        TextFile prueba = new TextFile();
        prueba.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Employees.txt");
        String line =  prueba.readLine();
        String[] columnas = line.split(",");
        String selec="employees_ID,first_name,department_id,DEPARtAMENT_ID,location_ID";
        String[] seleccion = selec.split(",");
        ArrayList<cabeza> cabezas = new ArrayList<>();
        
        for (int i = 1; i < columnas.length-2; i+=3) {
            cabezas.add(new cabeza(columnas[i], Integer.parseInt(columnas[i+1]),Integer.parseInt(columnas[i+2])));
        }
        
        TextFile prueba2 = new TextFile();
        prueba2.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Departmets.txt");
        String line2 =  prueba2.readLine();
        String[] columnas2 = line2.split(",");
        ArrayList<cabeza> cabezas2 = new ArrayList<>();
        
        
        for (int i = 1; i < columnas2.length-2; i+=3) {
            cabezas2.add(new cabeza(columnas2[i], Integer.parseInt(columnas2[i+1]), Integer.parseInt(columnas2[i+2])));
        }
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" ");//n0
        
        for (int i = 0; i < cabezas.size(); i++) {
            for (int j = 0; j < seleccion.length; j++) {
                if (cabezas.get(i).getNombre().equalsIgnoreCase(seleccion[j])) {
                    System.out.println(cabezas.get(i).getNombre());
                    model.addColumn(cabezas.get(i).getNombre());    
                }
            }
            
        }
        for (int i = 0; i < cabezas2.size(); i++) {
            for (int j = 0; j < seleccion.length; j++) {
                if (cabezas2.get(i).getNombre().equalsIgnoreCase(seleccion[j])) {
                    System.out.println(cabezas2.get(i).getNombre());
                    model.addColumn(cabezas2.get(i).getNombre());    
                }
            }
        }
        
        int cont=1;
        
        while ((line = prueba.readLine()) != null) {
            Object a[] = new Object[6];
            
          
            a[0]=cont;
            int aux=0;
            int T1=1;
            for (int i = 0; i < cabezas.size(); i++) {
                for (int j = 0; j < seleccion.length; j++) {
                    if (cabezas.get(i).getNombre().equalsIgnoreCase(seleccion[j])) {
                        a[T1]=line.substring(cabezas.get(i).getA(), cabezas.get(i).getB());
                        T1++;
                        
                    }
                }
                
            }
            prueba2.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\DescriptorDeArchivos\\src\\p\\Departmets.txt");
            line2 =  prueba2.readLine();
            line2 =  prueba2.readLine();
            while ((line2=prueba2.readLine())!=null) {                
                a[0]=cont;
                T1=4;
                for (int j = 0; j <cabezas2.size(); j++) {
                    for (int i = 0; i < seleccion.length; i++) {
                        if (cabezas2.get(j).getNombre().equalsIgnoreCase(seleccion[i])) {
                            a[T1]=line2.substring(cabezas2.get(j).getA(), cabezas2.get(j).getB());
                            T1++;
                        }
                    }
                    
                    
                }
                
                model.addRow(a);
                cont++;
            }
            
        }
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(324, 324, 324))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            consulta2_4 ventana;
            ventana = new consulta2_4();
            ventana.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(consulta2_3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
