/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wayne
 */
public class consulta2 extends javax.swing.JFrame {

    /**
     * Creates new form consulta2
     */
    public consulta2() throws IOException {
        initComponents();
        
        ArrayList<Employee> tuplas = new ArrayList<>();
        ArrayList<Department> tuplasDes = new ArrayList<>();
        
        TextFile prueba = new TextFile();
        TextFile prueba2 = new TextFile();
        //System.out.println(prueba.openRead("/Employees.txt"));
        prueba.openRead("/home/wayne/NetBeansProjects/P/src/p/Employees.txt");
        prueba2.openRead("/home/wayne/NetBeansProjects/P/src/p/Departments.txt");
        
        String line = null;
        int ii=0;
        while ((line = prueba.readLine()) != null) {
            System.out.println(line);
            tuplas.add(new Employee(line));
            ii++;
        }
        prueba.closeRead();
        
        while ((line = prueba2.readLine()) != null) {
            System.out.println(line);
            tuplasDes.add(new Department(line));
            ii++;
        }
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" ");//n0
        model.addColumn("EMPLOYEE_ID");//n0
        model.addColumn("FIRST_NAME");//n0
        model.addColumn("DEPARTMENT_ID");//n0
        model.addColumn("DEPARTMENT_ID_1");//n0
        model.addColumn("LOCATION_ID");//n0
        
        int cont=0;
        for (int i = 1; i < tuplas.size(); i++) {
            for (int j = 0; j < tuplasDes.size(); j++) {
                
                if (tuplas.get(i).getDepartmentID().equals(tuplasDes.get(j).getDEPARTMENT_ID())) {
                    cont++;
                    model.addRow(new Object[]{cont,tuplas.get(i).getEmployeeID(),tuplas.get(i).getFirstName(),tuplas.get(i).getDepartmentID(),tuplasDes.get(j).getDEPARTMENT_ID(),
                            tuplasDes.get(j).getLOCATION_ID()});
                    
                }
            }
        }
        jTable1.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(880, 310));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 860, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
