/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wayne
 */
public class tabla extends javax.swing.JFrame {

    /**
     * Creates new form tabla
     */
    public tabla() throws IOException {
        initComponents();
        
        
        TextFile prueba = new TextFile();
        prueba.openRead("C:\\Users\\Aw\\Documents\\Escuela\\Otoño 2020\\Base de Datos\\P\\src\\p\\Employees.txt");
        String line =  prueba.readLine();
        String[] columnas = line.split(",");
        ArrayList<cabeza> cabezas = new ArrayList<>();
        
        for (int i = 1; i < columnas.length-2; i++) {
            cabezas.add(new cabeza(columnas[i], Integer.parseInt(columnas[i+1]),Integer.parseInt(columnas[i+2])));
        }
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" ");//n0
        model.addColumn("EMPLOYEE_ID");//n0
        model.addColumn("FIRST_NAME");//n0
        model.addColumn("SALARY");//n0
        
        int cont=0;
       /* for (int i = 0; i < tuplas.size(); i++) {
            if (tuplas.get(i).getDepartmentID().equals("90")) {
                cont++;
                model.addRow(new Object[]{cont,tuplas.get(i).getEmployeeID(),tuplas.get(i).getFirstName(),tuplas.get(i).getSalary()});
            }
        }*/
        jTable1.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 750, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
